server:

  persistentVolume:

    name: "vmetrics-pv"
    
    # -- Create/use Persistent Volume for server component. Empty dir if false
    enabled: true

    # -- Array of access modes. Must match those of existing PV or dynamic provisioner. Ref: [http://kubernetes.io/docs/user-guide/persistent-volumes/](http://kubernetes.io/docs/user-guide/persistent-volumes/)
    accessModes:
      - ReadWriteOnce
    
    # -- Persistant volume annotations
    annotations: {}

    # -- StorageClass to use for persistent volume. Requires server.persistentVolume.enabled: true. If defined, PVC created automatically
    storageClass: "local-storage"

    # -- Mount path. Server data Persistent Volume mount root path.
    mountPath: /vmetrics-data

    # -- Size of the volume. Better to set the same as resource limit memory property.
    size: 250Mi