server:
  
  image:
    # -- Image repository
    repository: victoriametrics/victoria-metrics
    

  persistentVolume:

    name: "vmetrics-pv"
   
    # -- Array of access modes. Must match those of existing PV or dynamic provisioner. Ref: [http://kubernetes.io/docs/user-guide/persistent-volumes/](http://kubernetes.io/docs/user-guide/persistent-volumes/)
    accessModes:
      - ReadWriteOnce
    
    # -- Persistant volume annotations
    annotations: {}

    # -- StorageClass to use for persistent volume. Requires server.persistentVolume.enabled: true. If defined, PVC created automatically
    storageClass: "local-storage"

    # -- Mount path. Server data Persistent Volume mount root path.
    mountPath: /vmetrics-data

    # -- Size of the volume. Better to set the same as resource limit memory property.
    size: 250Mi

  persistentVolumeClaim:

   # -- Persistant volume claim annotations
    annotations: {}

    name: "vmetrics-pvc"
    storageClass: "local-storage"
    size: 250Mi

  StatefulSet:
    name: "vmetrics-statefulset"
    serviceName: "victoria-metrics-service"
