apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.server.persistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.server.persistentVolume.size | quote }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /swarajitroy-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube