apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.server.persistentVolumeClaim.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.persistentVolumeClaim.size | quote }}
  storageClassName: {{ .Values.server.persistentVolume.storageClass }}